//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoaDonDienNuoc
    {
        public int idHoaDon { get; set; }
        public int idPhong { get; set; }
        public Nullable<int> thang { get; set; }
        public string thanhToan { get; set; }
    
        public virtual quanLiPhong quanLiPhong { get; set; }
    }
}
