//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai2
{
    using System;
    using System.Collections.Generic;
    
    public partial class quanLiHoSoSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quanLiHoSoSinhVien()
        {
            this.hoaDonPhongs = new HashSet<hoaDonPhong>();
        }
    
        public int maSinhVien { get; set; }
        public byte[] hinhAnh { get; set; }
        public string hoTen { get; set; }
        public string diaChi { get; set; }
        public string gioiTinh { get; set; }
        public string khoa { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string soDienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoaDonPhong> hoaDonPhongs { get; set; }
    }
}
