//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai2
{
    using System;
    using System.Collections.Generic;
    
    public partial class quanLiPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quanLiPhong()
        {
            this.hoaDonPhongs = new HashSet<hoaDonPhong>();
            this.hoaDonDienNuocs = new HashSet<hoaDonDienNuoc>();
        }
    
        public int idPhong { get; set; }
        public string tinhTrang { get; set; }
        public Nullable<int> sucChua { get; set; }
        public Nullable<int> dangThue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoaDonPhong> hoaDonPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoaDonDienNuoc> hoaDonDienNuocs { get; set; }
    }
}
